"""initial_schema

Revision ID: 943cfa101009
Revises: 
Create Date: 2026-09-13 02:10:11.256874
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '943cfa101009'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('active_revision', sa.Integer(), nullable=False),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pipeline_config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('translation_json', sa.JSON(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('media_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_project_id'), 'media_assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_media_assets_sha256'), 'media_assets', ['sha256'], unique=False)
    op.create_table('pipeline_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_artifacts_input_hash'), 'pipeline_artifacts', ['input_hash'], unique=False)
    op.create_index(op.f('ix_pipeline_artifacts_project_id'), 'pipeline_artifacts', ['project_id'], unique=False)
    op.create_index('uq_pipeline_artifact_kind_input', 'pipeline_artifacts', ['project_id', 'kind', 'input_hash'], unique=True)
    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('progress_0_100', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_heartbeat_at'), 'processing_jobs', ['heartbeat_at'], unique=False)
    op.create_index(op.f('ix_processing_jobs_input_hash'), 'processing_jobs', ['input_hash'], unique=False)
    op.create_index(op.f('ix_processing_jobs_project_id'), 'processing_jobs', ['project_id'], unique=False)
    op.create_index('ix_processing_jobs_queue', 'processing_jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_table('speakers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speakers_project_id'), 'speakers', ['project_id'], unique=False)
    op.create_index('uq_speaker_project_label', 'speakers', ['project_id', 'label'], unique=True)
    op.create_table('chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('speaker_id', sa.String(length=36), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('vad_confidence', sa.Float(), nullable=True),
    sa.Column('diarization_confidence', sa.Float(), nullable=True),
    sa.Column('boundary_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_ms > start_ms', name='check_chunk_end_after_start'),
    sa.CheckConstraint('start_ms >= 0', name='check_chunk_start_nonnegative'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_project_id'), 'chunks', ['project_id'], unique=False)
    op.create_index('ix_chunks_project_order', 'chunks', ['project_id', 'order_index'], unique=True)
    op.create_index(op.f('ix_chunks_speaker_id'), 'chunks', ['speaker_id'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('model_revision', sa.String(length=255), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('peak_vram_mb', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_input_hash'), 'model_runs', ['input_hash'], unique=False)
    op.create_index(op.f('ix_model_runs_job_id'), 'model_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_model_runs_project_id'), 'model_runs', ['project_id'], unique=False)
    op.create_table('chunk_texts',
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('asr_raw', sa.Text(), nullable=True),
    sa.Column('asr_normalized', sa.Text(), nullable=True),
    sa.Column('reference_text', sa.Text(), nullable=True),
    sa.Column('reference_status', sa.String(length=32), nullable=False),
    sa.Column('furigana_json', sa.JSON(), nullable=True),
    sa.Column('furigana_status', sa.String(length=32), nullable=False),
    sa.Column('translation_vi', sa.Text(), nullable=True),
    sa.Column('translation_status', sa.String(length=32), nullable=False),
    sa.Column('translation_context_hash', sa.String(length=64), nullable=True),
    sa.Column('asr_input_hash', sa.String(length=64), nullable=True),
    sa.Column('furigana_input_hash', sa.String(length=64), nullable=True),
    sa.Column('translation_input_hash', sa.String(length=64), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('blank_spec_json', sa.JSON(), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('reference_revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_chunk_id'), 'exercises', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_exercises_project_id'), 'exercises', ['project_id'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('normalized_answer', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('strict_score', sa.Float(), nullable=True),
    sa.Column('diff_json', sa.JSON(), nullable=False),
    sa.Column('revealed_answer', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_exercise_id'), 'attempts', ['exercise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempts_exercise_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_exercises_project_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_chunk_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_table('chunk_texts')
    op.drop_index(op.f('ix_model_runs_project_id'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_job_id'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_input_hash'), table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index(op.f('ix_chunks_speaker_id'), table_name='chunks')
    op.drop_index('ix_chunks_project_order', table_name='chunks')
    op.drop_index(op.f('ix_chunks_project_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('uq_speaker_project_label', table_name='speakers')
    op.drop_index(op.f('ix_speakers_project_id'), table_name='speakers')
    op.drop_table('speakers')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_queue', table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_project_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_input_hash'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_heartbeat_at'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index('uq_pipeline_artifact_kind_input', table_name='pipeline_artifacts')
    op.drop_index(op.f('ix_pipeline_artifacts_project_id'), table_name='pipeline_artifacts')
    op.drop_index(op.f('ix_pipeline_artifacts_input_hash'), table_name='pipeline_artifacts')
    op.drop_table('pipeline_artifacts')
    op.drop_index(op.f('ix_media_assets_sha256'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_project_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_table('translation_cache')
    op.drop_table('projects')
    op.drop_table('app_settings')
    # ### end Alembic commands ###

